filter:
  paths: [src/*]
  excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer install --dev --prefer-source'

build:
  environment:
    postgresql: false
    mysql: false
    redis: false
    variables:
      XDEBUG_MODE: coverage
  tests:
    override:
      - php-scrutinizer-run
      - command: ./vendor/bin/phpunit
        coverage:
          file: build/coverage.xml
          format: clover
  nodes:
    php81:
      environment:
        php:
          version: 8.1
      tests:
        override:
          - php-scrutinizer-run
          - command: ./vendor/bin/phpunit
    php82:
      environment:
        php:
          version: 8.2
      tests:
        override:
          - php-scrutinizer-run
          - command: ./vendor/bin/phpunit
    php83:
      environment:
        php:
          version: 8.3
      tests:
        override:
          - php-scrutinizer-run
          - command: ./vendor/bin/phpunit