name: CI

on: [ push ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7,4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          version: 9
          configuration: phpunit.xml
          php_extensions: "xdebug"
          coverage_clover: "build/coverage.xml"
    